# Generated by Django 3.2.4 on 2022-01-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='Product_beato',
        ),
    ]
