# Generated by Django 3.2.4 on 2022-01-12 08:19

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_classname_product_beato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_beato',
            name='volume',
            field=models.IntegerField(default=product.models.Product_Beato.quantity),
        ),
    ]
