# Generated by Django 3.2.4 on 2022-01-12 08:56

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_beato_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_beato',
            name='volume',
            field=models.IntegerField(blank=True, default=product.models.Product_Beato.quantity),
        ),
    ]
