# Generated by Django 3.2.4 on 2022-01-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_beato_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_beato',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
